### ISSUE TITLE
ESLint crashing after upgrade to xo@0.16.0

### ISSUE THREAD

**Issue by maxrimue** [sindresorhus/xo#128]
I have a project where I've been using xo@0.15.0, and everything worked fine. Then, I upgraded to xo@0.16.0, and suddenly just running xo doesn't work anymore. I get the following output:
```shell
> node-autostart@3.0.1 test /Users/maxr/node-autostart
> xo && nyc mocha

TypeError: Cannot read property 'type' of undefined
    at getScopeBody (/Users/maxr/node-autostart/node_modules/eslint-plugin-import/lib/rules/newline-after-import.js:30:11)
    at /Users/maxr/node-autostart/node_modules/eslint-plugin-import/lib/rules/newline-after-import.js:104:27
    at Array.forEach (native)
    at /Users/maxr/node-autostart/node_modules/eslint-plugin-import/lib/rules/newline-after-import.js:103:22
    at Array.forEach (native)
    at EventEmitter.ProgramExit (/Users/maxr/node-autostart/node_modules/eslint-plugin-import/lib/rules/newline-after-import.js:99:14)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.leaveNode (/Users/maxr/node-autostart/node_modules/eslint/lib/util/node-event-generator.js:49:22)
    at CodePathAnalyzer.leaveNode (/Users/maxr/node-autostart/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:627:23)
    at CommentEventGenerator.leaveNode (/Users/maxr/node-autostart/node_modules/eslint/lib/util/comment-event-generator.js:110:23)
    at Controller.traverser.traverse.leave (/Users/maxr/node-autostart/node_modules/eslint/lib/eslint.js:908:36)
npm ERR! Test failed.  See above for more details.
```

It looks like the importing of an ESLint plugin is now failing.

My config, if important:
```json
  "xo": {
    "space": true,
    "rules": {
      "no-unused-expressions": 0,
      "no-undef": 0,
      "xo/filename-case": 0
    }
  }
```

If I downgrade to xo@0.15.0, everything works, but when I upgrade again it crashes again.
The PR that involves this upgrade can be found [here](https://github.com/maxrimue/node-autostart/pull/23), and the repo [here](https://github.com/maxrimue/node-autostart/). 

Thanks!

**Comment by sindresorhus** [comment]
Thanks for reporting :) Looks like https://github.com/benmosher/eslint-plugin-import/issues/386. Would you be able to track down the problematic code and post in that thread?

**Comment by maxrimue** [comment]
@sindresorhus I'll see if I can find out anything

**Comment by sindresorhus** [comment]
This should already be fixed. See the linked issue.
