### ISSUE TITLE
xo doesn't work on node v0.10.28

### ISSUE THREAD

**Issue by fruch** [sindresorhus/xo#153]
```
$ ./node_modules/.bin/xo --help

.\node_modules\xo\cli.js:4
const debug = require('debug')('xo');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

tried it like that:
```
 node --harmony ./node_modules/xo/cli.js
```

and still no luck:
```
$ node --harmony ./node_modules/xo/cli.js

.\node_modules\xo\cli.js:26
const cli = meow(`
                 ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

```

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/xo/releases/tag/v0.17.0
