### ISSUE TITLE
Using `"esnext": true` or `--esnext` throws error

### ISSUE THREAD

**Issue by markogresak** [sindresorhus/xo#17]
```
/usr/local/Cellar/nvm/0.25.4/versions/node/v0.12.7/lib/node_modules/xo/cli.js:76
		throw err;
		      ^
TypeError: Cannot read property 'type' of undefined
    at /usr/local/Cellar/nvm/0.25.4/versions/node/v0.12.7/lib/node_modules/xo/node_modules/eslint/lib/rules/quote-props.js:116:20
    at Array.forEach (native)
    at checkConsistency (/usr/local/Cellar/nvm/0.25.4/versions/node/v0.12.7/lib/node_modules/xo/node_modules/eslint/lib/rules/quote-props.js:112:25)
    at EventEmitter.ObjectExpression (/usr/local/Cellar/nvm/0.25.4/versions/node/v0.12.7/lib/node_modules/xo/node_modules/eslint/lib/rules/quote-props.js:156:17)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter (/usr/local/Cellar/nvm/0.25.4/versions/node/v0.12.7/lib/node_modules/xo/node_modules/eslint/lib/eslint.js:824:25)
    at Controller.__execute (/usr/local/Cellar/nvm/0.25.4/versions/node/v0.12.7/lib/node_modules/xo/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/usr/local/Cellar/nvm/0.25.4/versions/node/v0.12.7/lib/node_modules/xo/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/usr/local/Cellar/nvm/0.25.4/versions/node/v0.12.7/lib/node_modules/xo/node_modules/eslint/lib/eslint.js:817:24)
    at processText (/usr/local/Cellar/nvm/0.25.4/versions/node/v0.12.7/lib/node_modules/xo/node_modules/eslint/lib/cli-engine.js:199:27)
```

As you might have figured out from the paths, I'm using node `v0.12.7` (had to make a switch from iojs) and I'm using OS X (Yosemite). 
Removing said options will successfully lint, or better said unsuccessfully since it errors on bunch of es2015 syntax.

**Comment by sindresorhus** [comment]
Hmm, weird. I can't reproduce. Using the latest version (are you on latest?) of `$ xo --esnext` on some ES2015 code works fine for me. Can you share a code snippet that reproduces it? Looks like the error is coming from ESLint though.

**Comment by markogresak** [comment]
I'm using `v0.7.1`, I had to install everything since I'm usually using iojs and it's packages aren't shared with other nvm versions.

I've managed to single out the file, it's this one ([js/reducers/Sample.js](https://github.com/less-game/frontend/blob/master/js/reducers/Sample.js)):

```js
import * as ActionTypes from '../constants/ActionTypes';

const defaultState = {
  title: 'Home',
};

export default function(state = defaultState, action) {
  switch (action.type) {
  case ActionTypes.TITLE_CHANGED:
    return {...state, title: action.text};
  default:
    return state;
  }
}
```

**Comment by joakimbeng** [comment]
I've found out this was caused by the object rest spread syntax, have submitted a [PR to Eslint now](https://github.com/eslint/eslint/pull/3594)
