### ISSUE TITLE
vim-autoformat issue with overrides option

### ISSUE THREAD

**Issue by niftylettuce** [sindresorhus/xo#243]
@sindresorhus I think you use the [vim-autoformat](https://github.com/Chiel92/vim-autoformat) plugin too, so perhaps you could easily reproduce this.  Simply use the vim-autoformat plugin in combination with an overrides block in your `package.json` `xo` config.

Here was my `package.json` "xo" configuration...

```js
  // ...
  "xo": {
    "extends": "prettier",
    "plugins": [
      "babel",
      "prettier"
    ],
    "rules": {
      "prettier/prettier": [
        "error",
        {
          "singleQuote": true
        }
      ],
      "max-len": [
        "error",
        80,
        2
      ]
    },
    "parser": "babel-eslint",
    "space": true,
    "overrides": [
      {
        "files": "src/assets/js/*.js",
        "envs": [
          "browser",
          "es6"
        ]
      }
    ]
  },
  // ...
```

Error output upon file save:

```log
Formatter xo_javascript has errors: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.relative (path.js:1255:5)
    at Object.exports.lintText (/Users/niftylettuce/Public/lad/node_modules/xo/index.js:18:25)
    at getStdin.then.str (/Users/niftylettuce/Public/lad/node_modules/xo/cli.js:163:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Definition in 'g:formatdef_xo_javascript' was unsuccessful.
```

**Comment by niftylettuce** [comment]
not able to repro
