### ISSUE TITLE
The `ignores` option requires the `filename` option to be defined

### ISSUE THREAD

**Issue by niftylettuce** [sindresorhus/xo#244]
Input (inside package.json):

```js
  "xo": {
    "extends": "prettier",
    "plugins": ["babel", "prettier"],
    "parser": "babel-eslint",
    "rules": {
      "prettier/prettier": [
        "error",
        {
          "singleQuote": true,
          "bracketSpacing": true,
          "trailingComma": "none"
        }
      ],
      "max-len": [
        "error",
        {
          "code": 80,
          "ignoreUrls": true
        }
      ]
    },
    "ignores": [
      "schemas/**",
      "assets/public/bower/**",
      "assets/public/js/vendor/**",
      "assets/public/js/templates/**",
      "cache/**"
    ],
    "space": true
  },
```

Output:

```log
Formatter xo_javascript has errors: Error: The `ignores` option requires the `filename` option to be defined.
    at Object.exports.lintText (/Users/niftylettuce/Public/test/node_modules/xo/index.js:37:11)
    at getStdin.then.str (/Users/niftylettuce/Public/test/node_modules/xo/cli.js:163:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by sindresorhus** [comment]
You have to specify the `--stdin-filename` flag.

**Comment by niftylettuce** [comment]
Does this need patched in vim-autoformat perhaps @sindresorhus?  I'm just using it in package.json and running it.

**Comment by niftylettuce** [comment]
Ah, this makes sense, because you have to know what the current file name is for ignoring.  I'll submit a PR to vim-autoformat perhaps.

**Comment by sindresorhus** [comment]
Closing as this was fixed in `vim-autoformat`.
