### ISSUE TITLE
Error: Failed to load plugin ava: Cannot find module 'eslint-plugin-ava'

### ISSUE THREAD

**Issue by dtolstyi** [sindresorhus/xo#259]
Hi,

I got a simple nodejs project with a few files. I've followed instructions and installed xo: 
```
npm install --save-dev xo
```
And added script to `package.json`:
```js
"scripts": {
    "test": "xo"
  },
``` 
After running `npm test` I got an error:
```
$ npm test

> chromium@0.9.1 test D:\dev\node-chromium
> xo

Error: Failed to load plugin ava: Cannot find module 'eslint-plugin-ava'
Referenced from:
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.resolve (internal/module.js:27:19)
    at Object.load (D:\dev\node-chromium\node_modules\eslint\lib\config\plugins.js:134:29)
    at Array.forEach (native)
    at Object.loadAll (D:\dev\node-chromium\node_modules\eslint\lib\config\plugins.js:162:21)
    at load (D:\dev\node-chromium\node_modules\eslint\lib\config\config-file.js:541:21)
    at configExtends.reduceRight (D:\dev\node-chromium\node_modules\eslint\lib\config\config-file.js:424:36)
    at Array.reduceRight (native)
    at Object.applyExtends (D:\dev\node-chromium\node_modules\eslint\lib\config\config-file.js:408:28)
    at loadConfig (D:\dev\node-chromium\node_modules\eslint\lib\config.js:59:37)
npm ERR! Test failed.  See above for more details.
```
I've checked `./node_modules/xo/node_modules/eslint-plugin-ava/` and it's present there, but somehow **xo** doesn't see it.

**Comment by sindresorhus** [comment]
Make sure you’re on the latest Node.js and npm version, and try again. Earlier npm5 releases are very buggy.

**Comment by dtolstyi** [comment]
Thanks. I've updated `node` and `npm` to latest versions, removed `node_modules` and reinstalled evertying from scratch and now it works. 
The issue can be closed.
Thank you!

**Comment by JamesMGreene** [comment]
I'm still experiencing this issue with the latest Node and NPM, and cleaned `node_modules` and NPM cache. :confused:

```
npm: '5.5.1'
node: '8.7.0'
```

```
> xo

Error: Failed to load plugin ava: Cannot find module 'eslint-plugin-ava'
Referenced from:
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.load (C:\my-module\node_modules\eslint\lib\config\plugins.js:134:29)
    at Array.forEach (<anonymous>)
    at Object.loadAll (C:\my-module\node_modules\eslint\lib\config\plugins.js:162:21)
    at load (C:\my-module\node_modules\eslint\lib\config\config-file.js:541:21)
    at configExtends.reduceRight (C:\my-module\node_modules\eslint\lib\config\config-file.js:424:36)
    at Array.reduceRight (<anonymous>)
    at Object.applyExtends (C:\my-module\node_modules\eslint\lib\config\config-file.js:408:28)
    at loadConfig (C:\my-module\node_modules\eslint\lib\config.js:59:37)
npm ERR! Test failed.  See above for more details.
```

**Comment by JamesMGreene** [comment]
Got it to work after also removing the "package-lock.json" file.
