### ISSUE TITLE
ESLint 2

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/xo#79]
I'm [working](https://github.com/sindresorhus/xo/commit/be020e490cd53785610a50f3c5f10a264f16bada) on upgrading to [ESLint 2](http://eslint.org/blog/2016/02/eslint-v2.0.0-released). I've already upgraded [eslint-config-xo](https://github.com/sindresorhus/eslint-config-xo) with required changes and some new rules.

I've hit two issues. Tests don't pass and not exactly sure why. And it seems to be a problem with `babel-eslint` as async functions no longer parse (Just try running latest master on [boxen-cli](https://github.com/sindresorhus/boxen-cli)). Would appreciate some help getting this sorted out as I'm out of time and won't be able to get to this right now.

-

Stack trace for the failing tests:

```
TypeError: /Users/sindresorhus/dev/xo/test/options-manager.js: Cannot read property 'start' of undefined
    at /Users/sindresorhus/dev/xo/node_modules/babel-generator/lib/whitespace.js:29:19
    at Whitespace._findToken (/Users/sindresorhus/dev/xo/node_modules/babel-generator/lib/whitespace.js:99:30)
    at Whitespace.getNewlinesBefore (/Users/sindresorhus/dev/xo/node_modules/babel-generator/lib/whitespace.js:28:22)
    at CodeGenerator.printComment (/Users/sindresorhus/dev/xo/node_modules/babel-generator/lib/printer.js:321:34)
    at CodeGenerator.printComments (/Users/sindresorhus/dev/xo/node_modules/babel-generator/lib/printer.js:377:12)
    at CodeGenerator.printLeadingComments (/Users/sindresorhus/dev/xo/node_modules/babel-generator/lib/printer.js:231:10)
    at CodeGenerator.print (/Users/sindresorhus/dev/xo/node_modules/babel-generator/lib/printer.js:81:10)
    at CodeGenerator.printJoin (/Users/sindresorhus/dev/xo/node_modules/babel-generator/lib/printer.js:193:12)
    at CodeGenerator.printList (/Users/sindresorhus/dev/xo/node_modules/babel-generator/lib/printer.js:258:17)
    at CodeGenerator.ObjectExpression (/Users/sindresorhus/dev/xo/node_modules/babel-generator/lib/generators/types.js:48:10)
    at CodeGenerator._print (/Users/sindresorhus/dev/xo/node_modules/babel-generator/lib/printer.js:155:17)
    at CodeGenerator.print (/Users/sindresorhus/dev/xo/node_modules/babel-generator/lib/printer.js:91:10)
    at CodeGenerator.printJoin (/Users/sindresorhus/dev/xo/node_modules/babel-generator/lib/printer.js:193:12)
    at CodeGenerator.printList (/Users/sindresorhus/dev/xo/node_modules/babel-generator/lib/printer.js:258:17)
    at CodeGenerator.CallExpression (/Users/sindresorhus/dev/xo/node_modules/babel-generator/lib/generators/expressions.js:142:8)
    at CodeGenerator._print (/Users/sindresorhus/dev/xo/node_modules/babel-generator/lib/printer.js:155:17)
From previous event:
    at Api.run (/Users/sindresorhus/dev/xo/node_modules/ava/api.js:148:4)
    at Object.<anonymous> (/Users/sindresorhus/dev/xo/node_modules/ava/cli.js:115:5)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by sindresorhus** [comment]
Seems we need to wait on https://github.com/babel/babel-eslint/issues/254...

**Comment by sindresorhus** [comment]
Done.
